### ISSUE TITLE
User can browse current, upcoming and previous seasonal animes

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/ajax-project#1]
## ⚙️ Feature

User can browse current, upcoming and previous seasonal animes.

## 📐 Functionality

User will see currently airing animes upon page load.  User can change the animes displayed from a drop down menu in the navbar.

## 🖼️ Wireframes

![Screenshot 2023-04-25 at 1 45 23 PM](https://user-images.githubusercontent.com/23649469/234399547-ebf2ea1c-405b-466e-bfec-6656d27bca5b.png)
![Screenshot 2023-04-25 at 1 46 28 PM](https://user-images.githubusercontent.com/23649469/234399725-f3b267c4-3187-447f-b195-592a90b28cc1.png)

## ✅ Task List

- [x] Create the HTML for the header in the `header-container` so that it matches the figma example.
  - [x] Season will be a dropdown menu to select season aired
  - [x] Year will be a dropdown menu to select year aired
- [x] Create dummy anime entries to the unordered list in `data-view="anime-list"`. 
- [x] Complete the HTML form using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Add a 'click' event listener to info, play, bookmark buttons.
  - [x] Will open the respective modals.
- [x] Send request to Jikan api to pull currently airing anime. 
- [x] Define a function named `renderAnime` with a single parameter named `anime`. Function will generate and return a DOM tree for a single anime pulled from the Jikan api.
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the array pulled from Jikan api and generate a DOM tree for each anime in the array and append that DOM tree to the unordered list.
- [x] When Season and/or Year dropdown menu has been updated; request Jikan api for a new anime array for selected Season/Year
- [x] Render the DOM tree again with updated anime
  - [x] Update title to reflect currently shown anime lineup
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
