### ISSUE TITLE
User can watch the anime's trailer

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/ajax-project#2]
## ⚙️ Feature

User can watch the anime's trailer.

## 📐 Functionality

By clicking on the play button, a modal show a embed YouTube trailer for the anime

## 🖼️ Wireframes

![Screenshot 2023-04-29 at 3 26 31 PM](https://user-images.githubusercontent.com/23649469/235326602-ef436398-9652-4865-832f-d47838dc029d.png)

![Screenshot 2023-04-29 at 3 21 48 PM](https://user-images.githubusercontent.com/23649469/235326478-b2343272-71a4-4de6-8483-10b4c2d776a3.png)

## ✅ Task List

- [x] Update trailer modal to match wireframes
  - [x] Create an `iframe` element inside the modal with `src` attribute to anime's trailer.
- [x] Change `src` attribute based on which play button was clicked
  - [x] Reassigning `src` attribute to anime's trailer
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
