### ISSUE TITLE
User can bookmark an anime to their queue

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/ajax-project#3]
## ⚙️ Feature

User can add an anime to their watchlist.

## 📐 Functionality

After clicking on the bookmark icon, a prompt for that anime will ask if user wants to bookmark that anime. 
Once confirmed, user will be redirected to their bookmark list. 

## 🖼️ Wireframes

![Screenshot 2023-05-03 at 10 50 08 AM](https://user-images.githubusercontent.com/23649469/236002232-f2051be0-f379-4b79-a1ad-50709a0c23fc.png)

![Screenshot 2023-05-03 at 10 49 59 AM](https://user-images.githubusercontent.com/23649469/236002262-67615779-63c6-4ad5-a4a0-89c2500f5bc8.png)

## ✅ Task List

- [x]  In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
- [x] Create a new empty unordered list with `div[data-view="bookmark-list"]` element in the HTML.
- [x] Create some dummy anime entires to the unordered list in the HTML and style them to match the example entries in the figma. Each entry's content should be in a single `li` element within the `ul` element.
  - [x] If anime's episode count is null, then set progress caption to "0/unknown"
  - [x] Check example entries are responsive for both mobile and desktop screens.
- [x] Define a function named `renderBookmark` with a single parameter named `entry`. This parameter represents a single object for a single entry from the `data.entries` array. The function will generate and return a DOM tree for a single entry that matches the dummy anime entries.
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.bookmark` array and generate a DOM tree for each entry in the array, and append that DOM tree to the unordered bookmark list.
- [x] Create a function named `toggleNoEntries` which toggles the no entries text to show or hide when the function is called.
- [x] Create a new function named `viewSwap` with a single parameter representing the name of the view to show (the value will be either `"anime-list"` or `"bookmark-list"`). This function should show the view whose name was provided as an argument, as well as assign the string argument to the data.view property so that the currently showing view is tracked in the data model for the application.
- [x] `addEventListener` to `#bookmark-icon` in navbar that utilizes the `viewSwap` function to show the proper page.
  - [x] Change header text to 'Bookmarked Animes'.
- [x] Add `click` event listener to bookmark confirm button
  - [x] Adds anime object to `data.bookmark`
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
