### ISSUE TITLE
User can mark the episodes they watched

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/ajax-project#4]
## ⚙️ Feature

User can mark the episodes they have watched for a bookmarked anime.

## 📐 Functionality

With the plus and minus button, a user can mark the episode they last watched for an anime.

## 🖼️ Wireframes

<img width="361" alt="Screenshot 2023-05-03 at 9 32 45 PM" src="https://user-images.githubusercontent.com/23649469/236114625-e093cdeb-85d8-4931-8fe9-4f9a6b319477.png">

<img width="658" alt="Screenshot 2023-05-03 at 9 33 07 PM" src="https://user-images.githubusercontent.com/23649469/236114630-476d326b-42b8-47bf-b1ef-3fbf61e44d12.png">

## ✅ Task List

- [x] Add `click` event listener to `$bmList`.
  - [x] return if `event.target.tagName` is not an `i` element.
- [x] Add `click` event listener to both minus and plus buttons
  - [x] Increase or decrease the episode count by 1.
  - [x] Update progress' value attribute with episode count
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
