### ISSUE TITLE
User can delete an anime from their queue

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/ajax-project#5]
## ⚙️ Feature

User can delete an anime from their bookmark list

## 📐 Functionality

By clicking on the trash icon, a delete confirmation modal on appear. After confirming, selected anime will be removed from user's bookmark list.

## 🖼️ Wireframes

<img width="750" alt="Screenshot 2023-05-04 at 2 30 08 PM" src="https://user-images.githubusercontent.com/23649469/236334371-c7fe3e98-ff66-4147-916e-d16dd1eca76a.png">

<img width="1028" alt="Screenshot 2023-05-04 at 2 29 57 PM" src="https://user-images.githubusercontent.com/23649469/236334394-d3155dad-0395-48d9-a32f-21354d0b738d.png">

## ✅ Task List

- [x] Add event listener to the trash icon.
- [x] Show a delete confirmation modal when user clicks on the trash icon.
- [x] When the user clicks the xmark icon, hide the modal.
- [x] When the user clicks the check icon:
  - [x] Remove the corresponding entry in the `data.bookmark` array.
  - [x] Remove the anime `li` element from the DOM.
  - [x] conditionally use `toggleNoEntries` function to show the no entries text if needed.
  - [x] hide the modal.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
